fail_fast: true
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        exclude: ^(tests|examples|docsi|mypy_cache)/*
        additional_dependencies: [pep8-naming, flake8-docstrings]
        args: [--max-line-length=88, "--extend-ignore=D100,D101,D102,D103,D107,E203"]
